### ISSUE TITLE
ecc_star/ml build fails to find native_int/prims.ml

### ISSUE THREAD

**Issue by andres-erbsen** [mitls/hacl-star#1]
To: @jkzinzindohoue, the author of the commit of the relevant Makefile.

Hi,

I have been trying to build the extracted ML code snapshot of ecc_star using the instructions in https://github.com/mitls/hacl-star/blob/a8efac55f17f35923145cd26ef1ad6a64908bd5f/ecc_star/README.txt#L12. I believe I have ocaml and opam installed correctly (I used to get "missing package" errors and I don't anymore), but the build does not succeed.

First, the following path in `ecc_star/ml/Makefile` did not make sense for my system, so I changed it:

    -FSTAR_HOME=~/dev/old_fstar/FStar
    +FSTAR_HOME=/home/browse/hacl-star/FStar

After that, ocaml complained that `-O3` is not a known flag, so I removed it (this may be due to a version mismatch, but I am not sure that it is critical -- I installed opam last night, from https://opam.ocaml.org/doc/Install.html#Binarydistribution).

After that, I get an error that I would describe as the FStart git submodule and ecc_star/ml not matching up:

    browse@ashryn ~/hacl-star/ecc_star/ml (git)-[master] % make
    
    #######################################################
    #               Compiling CURVE25519                  #
    #######################################################
    
    cp ../curve_proof/ml/test_donna_64.ml ./c25519_64/test.ml
    cd ./c25519_64 && ocamlfind ocamlopt -package batteries -package stdint -linkpkg -g -thread -w -20-26-11 -I /home/browse/hacl-star/FStar/lib/ml/native_int -I /home/browse/hacl-star/FStar/lib/ml /home/browse/hacl-star/FStar/lib/ml/native_int/prims.ml /home/browse/hacl-star/FStar/lib/ml/FStar_Set.ml /home/browse/hacl-star/FStar/lib/ml/FStar_ST.ml /home/browse/hacl-star/FStar/lib/ml/FStar_All.ml FStar_FunctionalExtensionality.ml FStar_Seq.ml Parameters.ml IntLib.ml UInt.mli UInt.ml Bigint.mli Bigint.ml Eval.ml Modulo.ml Fsum.ml FsumWide.ml Fdifference.ml Fscalar.ml Fproduct.ml Bignum.ml ConcretePoint.ml DoubleAndAdd.ml MontgomeryLadder.ml  Crecip.ml test.ml
    File "/home/browse/hacl-star/FStar/lib/ml/native_int/prims.ml", line 1:
    Error: I/O error: /home/browse/hacl-star/FStar/lib/ml/native_int/prims.ml: No such file or directory
    make: *** [Makefile:53: test25519] Error 2
    browse@ashryn ~/hacl-star/ecc_star/ml (git)-[master] % find ~/hacl-star -name prims.ml                                                                    :(
    /home/browse/hacl-star/FStar/ulib/ml/prims.ml
    /home/browse/hacl-star/FStar/lib/ml/prims.ml

So it seems like `ecc_star/ml` expects `prims.ml` to be at `$FStar/lib/ml/native_int/prims.ml`, but the submodule has it at `$FStar/lib/ml/prims.ml`.

It would be nice if the correct version of FStar (or whatever is needed here) was included as a submodule or referenced in the README. Is there an easier way to build this, or should I be doing something different? 

Thanks,
Andres

**Comment by jkzinzindohoue** [comment]
Hi,
Sorry about that. The appropriate version is indicated later in the README but was not made very explicit. The submodule actually points to the current version of F*, incompatible with that code.
For convenience I added the proper library files locally, so hopefully you will now be able to run make successfully.
Could you please try and let me know ?
Best,
JK

**Comment by andres-erbsen** [comment]
This works. Thank you!
Fixed in fcac9996d29a7b27eee4fef541dd2c0d96180972.
