### ISSUE TITLE
Forgotten C export bundle prefix for HACL_HMAC_256_hmac  

### ISSUE THREAD

**Issue by denismerigoux** [mitls/hacl-star#109]
When exporting the `hacl-c` snapshot, the functions inside bundled module `Hacl.Hmac.Sha2.256` do not have the correct prefix. They are currently exported as `hmac` and `hmac_core`.

**Comment by beurdouche** [comment]
Fixed via: https://github.com/mitls/hacl-star/commit/894d0741d7411a0257cf2179ff30b9840e76d1ba
