### ISSUE TITLE
Don't use --expose_interfaces

### ISSUE THREAD

**Issue by franziskuskiefer** [mitls/hacl-star#114]
de96999197edda7ac15c2d3a2b19b45cf4fbf39b added `--expose_interfaces` to `specs/Makefile`. But it is not a feature FStar stable supports. If we want to use `--expose_interfaces`, we have to update to FStar master.

**Comment by beurdouche** [comment]
Ack, I think this should have been pushed to ‘dev_specs’. I’ll fix ASAP

**Comment by beurdouche** [comment]
Ok we moved this branch to use F* master. closing
