### ISSUE TITLE
quic_provider.c - warning C4456: declaration of 'nonce' hides previous local declaration

### ISSUE THREAD

**Issue by BarryBo** [mitls/hacl-star#125]
Note that 'nonce' is declared once at function scope, then again inside the switch statement, with a different type.

`int MITLS_CALLCONV quic_crypto_packet_number_otp(quic_key *key, const unsigned char *sample, unsigned char *mask)`
`{`
`  FStar_UInt128_uint128 nonce;`
`  switch(Crypto_Indexing_cipherAlg_of_id(key->id))`
`  {`
`    FStar_UInt128_t nonce;`
`    case Crypto_Indexing_CHACHA20:`

**Comment by ad-l** [comment]
Fixed in hacl eaab15f82c5a999edf1da08f2c4a1290965b545a
