### ISSUE TITLE
SHA2 rotate functions allow shifts by the bitwidth

### ISSUE THREAD

**Issue by tchajed** [mitls/hacl-star#22]
F*'s UInt libraries incorrectly allow clients to use `shift_left` and `shift_right` by more than the bitwidth, which is undefined in C and therefore should be disallowed.

Hacl* is relying on this behavior in three places, three rotation functions in the SHA2 implementations: [`rotate_right`](https://github.com/mitls/hacl-star/blob/master/code/hash/Hacl.Hash.SHA2_256.fst#L91-L92), and two copies of `rotate_right64`, [one in SHA2_384](https://github.com/mitls/hacl-star/blob/master/code/hash/Hacl.Hash.SHA2_384.fst#L100-L101) and [another in SHA2_512](https://github.com/mitls/hacl-star/blob/master/code/hash/Hacl.Hash.SHA2_512.fst#L97-L98).

Specifically, these functions assume `s <= 32` or `s <= 64` when they should have `s < 32` and `s < 64`. A quick perusal indicates that this won't affect verification since the shifts are in-bounds constants already.

**Comment by msprotz** [comment]
Once we merge HACL*'s migrating_sts_bis into master, and get a green on Everest, I'll change the function definitions on the F* side to be at least abstract, which should fix the immediate problem.

There's a question of whether the `s < 64 ==> ...` in the post-condition in the right style of specification, but I believe that can wait.

CC @nikswamy and @tahina-pro

**Comment by beurdouche** [comment]
Fixed by https://github.com/FStarLang/FStar/commit/f73f295ed0661faec205fdf7b76bdd85a2a94a32

**Comment by beurdouche** [comment]
This has been fixed on the HaCl* too.

**Comment by tchajed** [comment]
Specifically, it looks like this is fixed in [beurdouche_fix_shifts](https://github.com/mitls/hacl-star/commit/c8a61ab189ce163705f8f9ff51e41cab2869f6d6) - the change to F* doesn't really fix this issue, it actually just makes it worse by breaking verification.
