### ISSUE TITLE
Specs and Functional Correctness for secure_api primitives

### ISSUE THREAD

**Issue by sishtiaq** [mitls/hacl-star#3]
SPECS & FUNCTIONAL CORRECTNESS required at least for the primitives used in secure_api, with a Crypto.Foo.Spec.fst and Hacl.Foo.fsti in spec; and Hacl.Foo.fst in code. The primitives are: 

- [x] POLY1305 mostly done, but we may want to keep 32-bit stuff. And we still need a nice imperative fsti.
- [x] Chacha20 (proof TODO on fast code). I propose we share `specs/experimental/Hacl.Spec.Chacha20.fst` (renamed to Crypto.Spec…). I have started to use it in the AEAD proof, so that we can switch between fully correct implementations after security verification. I hope we don’t need an intermediate spec within salsa-family.
- [ ] GF128 done? But still experimental; what’s missing? Why do we have two copies of the GF spec?
- [ ] AES128, AES256 (?)
- [ ] `Hashing.*` to migrate from mitls-fstar to hacl-star, in the same style, once the dust settles.

**Comment by beurdouche** [comment]
@s-zanella @markulf I am closing this issue because does not correspond to a specific HACL* task.
Can you please have a look here and eventually reopen issues for small independent tasks ? Thanks :)
