### ISSUE TITLE
Clean up the makefiles

### ISSUE THREAD

**Issue by jkzinzindohoue** [mitls/hacl-star#32]
Now that the repository is more stable we need to clean up the makefiles.

In particular:
- [x] `./Makefile`
- [x] `./test/Makefile`
- [x] `./test/c/Makefile` (which goes into the snapshot)
- [x] `./snapshots/Makefile`

**Comment by beurdouche** [comment]
Already started to improve on `./Makefile` as it is the main one...
The others have lower priority.

**Comment by beurdouche** [comment]
In particular, it is not clean at all for me why the snapshots targets are in the `test` Makefile...
This should definitely be moved out...

**Comment by beurdouche** [comment]
Ok taking a lock on all Makefiles, I will propose a PR for changes this weekend ;)
@jkzinzindohoue @protz @karthikbhargavan CC: @s-zanella

**Comment by beurdouche** [comment]
Still ongoing https://github.com/mitls/hacl-star/pull/40

**Comment by beurdouche** [comment]
Fixed https://github.com/mitls/hacl-star/commit/214738c59bd88a8dc36be305ce41438df283b87a
Main changes have been implemented, additional improvements welcome...
