### ISSUE TITLE
 (Error) 0 is not in the expected range for FStar.UInt32

### ISSUE THREAD

**Issue by wintersteiger** [mitls/hacl-star#45]
I got the following error when I opened `mitls-fstar/src/tls/CommonDH.fst`. Should I be concerned about this?

```
[F* error] Exception of type 'FStar.Errors+Error' was thrown.
[F* error]    at FStar.ToSyntax.ToSyntax.desugar_machine_integer(env env, String repr, signedness signedness, width width, range range)

...
[F* error]    at FStar.Interactive.interactive_mode'(String filename)
[F* error]    at FStar.Main.main[a]()
[F* error] F:\dev\sec\hacl-star\code\lib\kremlin\FStar.Endianness.fst(189,11-189,14): (Error) 0 is not in the expected range for FStar.UInt32
```

This is Windows-Emacs with interactive mode into F#-F*, which is likely at least part of the problem.

**Comment by s-zanella** [comment]
See #1053 and #1054. It's a known limitation of F#-F*, which uses F# bounded `int` type to compute machine integer ranges. In this case `pow2 32 - 1` overflows and wraps to `-1`, which causes F* to fail when checking that `0 <= -1`.
