### ISSUE TITLE
New primitive: implement 32-bit versions of Poly1305. 

### ISSUE THREAD

**Issue by sishtiaq** [mitls/hacl-star#5]
POLY1305. AEAD now uses a faster, verified 64-bit implementation; JK is working on a new 32-bit one that shares code and specs; we will independently keep the old verified one from low-level/crypto in some `old` subdirectory. (More generally, we should learn how to maintain multiple implementations within hacl*.)

**Comment by jkzinzindohoue** [comment]
A draft is currently in `hacl-star/code/experimental`, this is now high on the TODO list.

**Comment by beurdouche** [comment]
Done https://github.com/mitls/hacl-star/commit/3904b0d998f038376ca6016d6d7c8427bc0376be
