### ISSUE TITLE
A mirror repository for hacl-c snapshots

### ISSUE THREAD

**Issue by podhrmic** [mitls/hacl-star#52]
It would be useful to have a separate repository with the newest C snapshots. The use case is that I would like to include hacl-c in a separate project, but plain copy-paste doesn't seem sufficient because then later changes/bugfixes won't be reflected. Importing whole hacl-star repo is too heavy-weight since I need only a few C files. Ideal would be using a submodule pinned to a particular version of the hacl-c.

Is that something you would find useful?

**Comment by karthikbhargavan** [comment]
We are considering refactoring the repo, and ideas are welcome.
I am guessing that synching a read-only repository with the “stable” branch of hacl-star/snapshots would work for you?

**Comment by podhrmic** [comment]
yes that would be perfect.

**Comment by beurdouche** [comment]
Done. Note that it is just a first commit that might be restructured to add a `src` folder next week... TBD.

**Comment by beurdouche** [comment]
https://github.com/mitls/hacl-c
