### ISSUE TITLE
Restore use of the default kremlib files

### ISSUE THREAD

**Issue by beurdouche** [mitls/hacl-star#62]
Determine if we keep having FStar.h only before solving the issue here
- [ ] ~Extract all UInt128 definitions to a single FStar.h using `-static-header`~
- [ ] ~`FStar_UInt128_eq_mask` and `FStar_UInt128_gte_mask` are static functions but might be unused, which breaks builds with `-Werror -Wall`~

Additionally, discussions are needed about the number of files that we are willing to keep from kremlib

**Comment by msprotz** [comment]
I thought that things marked as `static inline` didn't trigger `-Wunused-function`? Certainly not all the uint128 functions from `kremlib.h` are used in every single translation unit, yet we don't get the warning?

Does the behavior depend on the compiler?

**Comment by beurdouche** [comment]
We solved these problems by generating `FStar.c` and `FStar.h` instead of using `-static-header`.
The second issue is solved because we don't static inline those definitions anymore.

As explained in https://github.com/FStarLang/kremlin/issues/69, we use the current version of `kremlib.h` with a special splitting until `kremlin/kremlib.h` is itself split.
