### ISSUE TITLE
Extend primitives: implementation of HMAC for SHA2_384 and SHA2_512

### ISSUE THREAD

**Issue by beurdouche** [mitls/hacl-star#67]
This can be done easily through code duplication for now.

**Comment by s-zanella** [comment]
The `dev_hkdf` branch contains a specification and implementation of `HMAC-SHA2-512` in `secure_api/hkdf/{Spec.HMAC.SHA2_512,Hacl.HMAC.SHA2_512}.fst`.

The specification comes with test vectors that extract to OCaml `Spec.Test.HMAC.SHA2_512.fst`.
I also wrote an F* file for driving tests for the agile implementation in `Crypto.HMAC.fst`. Contrary to the majority of tests we write by hand in C or OCaml, this file extracts to both OCaml and C. With better library support, I think this is a good style to strive for (see #64).

**Comment by msprotz** [comment]
for the record, I am extremely supportive of writing tests in F*; once you do that, you get test drivers for OCaml, C and Wasm... writing tests twice should be avoided as much as possible

**Comment by beurdouche** [comment]
I think that all my tests actually are in F*, but they are duplicated in Specs and Code.
I will look at the style suggested by Santiago and find the courage to move everything in HACL* towards that style at some point. Help welcome :)

**Comment by beurdouche** [comment]
This will happen with https://github.com/mitls/hacl-star/issues/70
