### ISSUE TITLE
CI for Chacha20 in WASM

### ISSUE THREAD

**Issue by beurdouche** [mitls/hacl-star#69]
Get info from Jonathan

**Comment by msprotz** [comment]
https://github.com/project-everest/everest-ci/issues/102

**Comment by beurdouche** [comment]
@denismerigoux I have the target for c-wasm in `Makefile.build` but the one I want is actually the one for `k-wasm`. Anyway you could PR adding that ? It would be useful to run `k-wasm` in the CI ;)

**Comment by beurdouche** [comment]
Let's follow that here: https://github.com/mitls/hacl-star/issues/79
