### ISSUE TITLE
Update kremlib.h

### ISSUE THREAD

**Issue by franziskuskiefer** [mitls/hacl-star#77]
`kremlib.h` has a couple issues that prevent NSS from updating the HACL* version.

- [x] Don't use `(__int128)` directly. https://github.com/mitls/hacl-star/blob/9aedca6969421b2e95fc967b4758bb4e7bf1a6b9/snapshots/hacl-c/kremlib.h#L415
- [ ] `FStar_UInt128_eq_mask` and `FStar_UInt128_gte_mask` are static functions but might be unused, which breaks builds with `-Werror -Wall`

**Comment by beurdouche** [comment]
The first one has been fixed upstream.
The second one is a work in progress...

**Comment by beurdouche** [comment]
Closing. Tracked by https://github.com/mitls/hacl-star/issues/62
