### ISSUE TITLE
Naming conventions should be aligned through specifications and code

### ISSUE THREAD

**Issue by sishtiaq** [mitls/hacl-star#9]
REVIEW NAMING. For instance Crypto.Symmetric.Chacha20.fst could become Crypto.Symmetric.Chacha20.Ref.fst (one extra suffix marking that it is not the main implementation).

**Comment by fournet** [comment]
Our current naming conventions are in ROADMAP.md; we may need to adjust them e.g. for bundled extraction.

**Comment by markulf** [comment]
I changed `external` to `other_providers` in ROADMAP.md to reflect the directory structure

**Comment by prosecco** [comment]
Within hacl-star/code we are considering dropping the Symmetric/EC sub-namespaces, and going straight for the primitive name. E.g. Hacl.Curve25519.fst and Hacl.Poly1305_64.fst etc. Modules in specs will be called Spec.Poly1305.fst and Spec.Curve25519.fst. 

Naming schemes for other bits is still a bit uncertain. I am assuming for now that secure_api will retain the Crypto prefix.

**Comment by beurdouche** [comment]
The current naming convention is coherent. A separate issue is opened regarding bundle names https://github.com/mitls/hacl-star/issues/55
