### ISSUE TITLE
printf should be replaced with KRML_HOST_PRINTF

### ISSUE THREAD

**Issue by podhrmic** [mitls/hacl-star#94]
Here https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/AEAD_Poly1305_64.c#L340
and here https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/AEAD_Poly1305_64.c#L346

The same for `exit` and KRML_HOST_EXIT here https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/AEAD_Poly1305_64.c#L341 and here https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/AEAD_Poly1305_64.c#L347

**Comment by beurdouche** [comment]
Ok, this file doesn't need to exist on its own as `Hacl_Poly1304_64` or `Hacl_Chacha20Poly1305` need to be called instead, so we expect to kill this file entirely as soon as we can. We need to rewrite Hacl_Chacha20Poly1305 first... This will solve your issue but it needs to be done properly.
I would suggest you do an ad-hoc patch in the mean time...

**Comment by beurdouche** [comment]
Fixed by https://github.com/FStarLang/kremlin/commit/ce23451dd7a68dd224bf943ac8dd2ab2b67c28ac
