### ISSUE TITLE
Update the C snapshot repository https://github.com/mitls/hacl-c

### ISSUE THREAD

**Issue by podhrmic** [mitls/hacl-star#95]
Would it be possible to update the snapshot with the latest C code?

**Comment by beurdouche** [comment]
Let me do that right now...

**Comment by beurdouche** [comment]
You should be good to go... There is a big change in terms of namespace (everything is now prefixed by `Hacl_`) in this refresh as I wanted to avoid name collision in NSS/Firefox.
Many small improvements have been done to silence warnings, I'll answer your questions in the opened issues asap...

Feel free to reopen when if you need another update ;)

**Comment by podhrmic** [comment]
OK, one more thing. I would like to be able to use the repository without any changes to the actual hacl-c code. My problem is that I have to change `kremlib.h` to include my definitions of `KRML_HOST_PRINTF` and `KRML_HOST_EXIT` (I add `#include "kremlib_embedded.h"`).

Since I don't want to change it every time I update hacl-c, I would like to add a flag, something like:

```
#if INCLUDE_HOST_DEFINES
#include HOST_DEFINES_HEADER
#endif
```

That way I can pass the flags and path to a header with my definitions from the makefile (`INCLUDE_HOST_DEFINES=1 HOST_DEFINES_HEADER=path/to/the/file/custom_definitons.h`)

For completeness, here are my definitions for a bare metal system:
```
#ifndef __KREMLIB_EMBEDDED_H
#define __KREMLIB_EMBEDDED_H

#define KRML_HOST_EXIT while
#define KRML_HOST_PRINTF(Fmt,...) snprintf(NULL, 0, Fmt, __VA_ARGS__);

#endif
```

**Comment by podhrmic** [comment]
@beurdouche what do you think about this fix?
