### ISSUE TITLE
Unable to build fstar-master

### ISSUE THREAD

**Issue by ae-g-i-s** [mitls/hacl-star#97]
Hello,

I'm trying to build mitls-fstar, but keep running into problems during the compilation of hacl-fstar's *LowCProvider-tmp* target.

I initially tried to compile with kremlin, hacl-fstar and mitls-fstar on the master branch, but got an error about a file for kremlin version 20 there (current version being 24). I tracked the current_version info from kremlin back to 20, but was unable to compile this version with a currrent FStar. So instead, I switched everything to fstar-master...but it fails in the same *make* target (although with a different error).

A few preliminaries...
> $ cd ~/FStar/ && git status
> Your branch is up-to-date with 'origin/master'.
> $ echo $FSTAR_HOME
> /home/ec2-user/FStar/
> $ which fstar.exe
> ~/FStar/bin/fstar.exe
> $ cd ~/kremlin && git status | head -1
> On branch fstar-master
> $ cd ~/hacl-star/ && git status | head -1
> On branch fstar-master
> $ cd ~/mitls-fstar/ && git status | head -1
> HEAD detached at origin/fstar-master

The only modifications are the Makefile in hacl-star (due to cmake) and a symlink from ~/mitls-fstar/.fstar to ~/FStar (because for some reason, git does not want to initialise that submodule).

Build output is attached.
[mitls-fstar.log](https://github.com/mitls/hacl-star/files/1539538/mitls-fstar.log) is the output of *make -C src/tls* in mitls-fstar, while [hacl-star.log](https://github.com/mitls/hacl-star/files/1539539/hacl-star.log) is the output of *make LowCProvider-tmp* in hacl-star/secure_api/ (the rest was already compiled previously and without errors). The latter is a subset of the former (because mitls-fstar tries to build exactly this target in hacl-star). All repositories were *make clean*ed before switching branch.

**Comment by msprotz** [comment]
LowCProvider is not tracked by kremlin's CI and I do recall someone saying that it was broken. While I take a look, an option for you is to use the latest known good set of hashes at https://github.com/project-everest/everest/blob/master/hashes.sh -- these are guaranteed to work together, i.e. build, run the tests successfully, and verify together.

**Comment by ae-g-i-s** [comment]
Thanks! Unfortunately, this only leads to new errors:
* `tyattrs` in src/extraction/ml/FStar_Extraction_ML_PrintML_4.05.X.ml:62 is undefined and leads to a compile error. I backported a later version of the file, using `metadata` instead, which allows it to compile.
* However, the pattern in https://github.com/FStarLang/FStar/blob/master/src/extraction/ml/FStar_Extraction_ML_PrintML_4.05.X.ml:217 fails to match when building hacl-fstar, again terminating the compilation. I'm not familiar enough with OCaml to fix this.

I also tried building via Docker, which also fails, but in different ways:
* File ownership for the mounted folder (see https://github.com/mitls/mitls-fstar/wiki/Setting-up-a-Docker-based-Development-environment#run-docker-image) is wrong, but that's probably distribution dependent and easy to fix.
* The Docker image does not set `FSTAR_HOME`, `KREMLIN_HOME` or `HACL_HOME`. `src/tls/Makefile` sets them to /home/FStar, /home/kremlin and /home/hacl-star, which do not exist.
* After manually setting FSTAR_HOME to `$HOME/FStar` (/home/FStar/FStar) and running `make -C src/tls all-ver -k -j 2`, compilation fails immediately due to Makefile:129, which uses the unrecognized option '--verify_module'.
* Running `make -C src/tls build -k -j 2` (which skips the verification) continues much further, including building the CoreCrypto module of FStar, but dies because ../../../hacl-star/ (HACL_HOME) does not exist.

**Comment by beurdouche** [comment]
I flagged the issue as wontfix because this is hopefully gonna happen naturally when moving HACL* to F* master in a few weeks...
